-- Tan Hong Kai S10256928K
CREATE OR ALTER TABLE ProductCategory (
    [PRODUCTCATEGORYKEY] [INT] NOT NULL PRIMARY KEY,
    [PRODUCTCATEGORYNAME] [VARCHAR](150) NOT NULL
);

CREATE OR ALTER TABLE ProductSubCategory (
    [PRODUCTSUBCATEGORYKEY] [INT] NOT NULL PRIMARY KEY,
    [PRODUCTSUBCATEGORYNAME] [VARCHAR](150) NOT NULL
);

CREATE OR ALTER TABLE Promotion (
    [PROMOTIONKEY] [INT] NOT NULL PRIMARY KEY,
    [PROMOTIONLABEL] [INT] NOT NULL UNIQUE,
    [PROMOTIONNAME] [VARCHAR](150) NOT NULL,
    [DISCOUNTPERCENT] [DECIMAL](5, 2) NOT NULL CHECK (DISCOUNTPERCENT >= 0 AND DISCOUNTPERCENT <= 1),
    [PROMOTIONTYPE] [VARCHAR](100) NOT NULL,
    [PROMOTIONCATEGORY] [VARCHAR](100) NOT NULL
);
