-- Tan Hong Kai S10256928K
CREATE OR REPLACE TABLE ProductCategory (
    PRODUCTCATEGORYKEY INTEGER NOT NULL PRIMARY KEY,
    PRODUCTCATEGORYNAME VARCHAR(150) NOT NULL
);

CREATE OR REPLACE TABLE ProductSubCategory (
    PRODUCTSUBCATEGORYKEY INTEGER NOT NULL PRIMARY KEY,
    PRODUCTSUBCATEGORYNAME VARCHAR(150) NOT NULL
);

CREATE OR REPLACE TABLE Promotion (
    PROMOTIONKEY INTEGER NOT NULL PRIMARY KEY,
    PROMOTIONLABEL INTEGER NOT NULL UNIQUE,
    PROMOTIONNAME VARCHAR(150) NOT NULL,
    DISCOUNTPERCENT DECIMAL(5, 2) NOT NULL,
    PROMOTIONTYPE VARCHAR(100) NOT NULL,
    PROMOTIONCATEGORY VARCHAR(100) NOT NULL
);

CREATE OR REPLACE TABLE SalesTerritory (
    SALESTERRITORYKEY INTEGER NOT NULL PRIMARY KEY,
    GEOGRAPHYKEY INTEGER NOT NULL,
    SALESTERRITORYNAME VARCHAR(150) NOT NULL,
    SALESTERRITORYREGION VARCHAR(150) NULL,
    SALESTERRITORYCOUNTRY VARCHAR(150) NULL,
    SALESTERRITORYGROUP VARCHAR(100) NULL,
    SALESTERRITORYLEVEL INTEGER NOT NULL,
    SALESTERRITORYMANAGER INTEGER NOT NULL,
    STATUS VARCHAR(50) NOT NULL,
    CONSTRAINT FK_GEOGRAPHY FOREIGN KEY (GEOGRAPHYKEY) REFERENCES GEOGRAPHY(GEOGRAPHYKEY),
    CONSTRAINT FK_EMPLOYEE FOREIGN KEY (SALESTERRITORYMANAGER) REFERENCES EMPLOYEE(EMPLOYEEKEY)
);

CREATE OR REPLACE TABLE Product (
    PRODUCTKEY INTEGER NOT NULL PRIMARY KEY,
    PRODUCTNAME VARCHAR(150) NOT NULL,
    PRODUCTDESCRIPTION TEXT NULL,
    PRODUCTSUBCATEGORYKEY INTEGER NOT NULL,
    MANUFACTURER VARCHAR(150) NULL,
    BRANDNAME VARCHAR(150) NULL,
    CLASSID INTEGER NULL,
    CLASSNAME VARCHAR(100) NULL,
    STYLEID INTEGER NULL,
    STYLENAME VARCHAR(100) NULL,
    COLORID INTEGER NULL,
    COLORNAME VARCHAR(50) NULL,
    WEIGHT DECIMAL(10,2) NULL,
    WEIGHTUNITMEASUREID VARCHAR(50) NULL,
    UNITOFMEASUREID VARCHAR(50) NULL,
    UNITOFMEASURENAME VARCHAR(50) NULL,
    STOCKTYPEID INTEGER NULL,
    STOCKTYPENAME VARCHAR(50) NULL,
    UNITCOST DECIMAL(10,2) NOT NULL,
    UNITPRICE DECIMAL(10,2) NOT NULL,
    AVAILABLEFORSALEDATE DATETIME NOT NULL,
    STATUS BOOLEAN NOT NULL,
    CONSTRAINT FK_PRODUCTSUBCATEGORY FOREIGN KEY (PRODUCTSUBCATEGORYKEY) REFERENCES PRODUCTSUBCATEGORY(PRODUCTSUBCATEGORYKEY)
);

-- Yong Yun Kai Louis 

-- Ang Wei Xuan Senderos 

-- Tan Jun Yu Zavier

-- Arjunan Yohith
