-- Tan Hong Kai S10256928K
CREATE TABLE [ProductCategory] (
    [PRODUCTCATEGORYKEY] [INT] NOT NULL PRIMARY KEY,
    [PRODUCTCATEGORYNAME] [VARCHAR](150) NOT NULL
);

CREATE TABLE [ProductSubCategory] (
    [PRODUCTSUBCATEGORYKEY] [INT] NOT NULL PRIMARY KEY,
    [PRODUCTSUBCATEGORYNAME] [VARCHAR](150) NOT NULL
);

CREATE TABLE [Promotion] (
    [PROMOTIONKEY] [INT] NOT NULL PRIMARY KEY,
    [PROMOTIONLABEL] [INT] NOT NULL UNIQUE,
    [PROMOTIONNAME] [VARCHAR](150) NOT NULL,
    [DISCOUNTPERCENT] [DECIMAL](5, 2) NOT NULL CHECK ([DISCOUNTPERCENT] >= 0 AND [DISCOUNTPERCENT] <= 1),
    [PROMOTIONTYPE] [VARCHAR](100) NOT NULL,
    [PROMOTIONCATEGORY] [VARCHAR](100) NOT NULL
);

CREATE TABLE [SalesTerritory] (
    [SALESTERRITORYKEY] [INT] NOT NULL PRIMARY KEY,
    [GEOGRAPHYKEY] [INT] NOT NULL,
    [SALESTERRITORYNAME] [VARCHAR](150) NOT NULL,
    [SALESTERRITORYREGION] [VARCHAR](150) NULL,
    [SALESTERRITORYCOUNTRY] [VARCHAR](150) NULL,
    [SALESTERRITORYGROUP] [VARCHAR](100) NULL,
    [SALESTERRITORYLEVEL] [INT] NOT NULL,
    [SALESTERRITORYMANAGER] [INT] NOT NULL,
    [STATUS] [VARCHAR](50) NOT NULL,
    CONSTRAINT [FK_SALESTERRITORY_GEOGRAPHY] FOREIGN KEY ([GEOGRAPHYKEY]) REFERENCES [GEOGRAPHY]([GEOGRAPHYKEY]),
    CONSTRAINT [FK_SALESTERRITORY_EMPLOYEE] FOREIGN KEY ([SALESTERRITORYMANAGER]) REFERENCES [EMPLOYEE]([EMPLOYEEKEY])
);

CREATE TABLE [Product] (
    [PRODUCTKEY] [INT] NOT NULL PRIMARY KEY,
    [PRODUCTNAME] [VARCHAR](150) NOT NULL,
    [PRODUCTDESCRIPTION] [TEXT] NULL,
    [PRODUCTSUBCATEGORYKEY] [INT] NOT NULL,
    [MANUFACTURER] [VARCHAR](150) NULL,
    [BRANDNAME] [VARCHAR](150) NULL,
    [CLASSID] [INT] NULL,
    [CLASSNAME] [VARCHAR](100) NULL,
    [STYLEID] [INT] NULL,
    [STYLENAME] [VARCHAR](100) NULL,
    [COLORID] [INT] NULL,
    [COLORNAME] [VARCHAR](50) NULL,
    [WEIGHT] [DECIMAL](10,2) NULL CHECK ([WEIGHT] >= 0),
    [WEIGHTUNITMEASUREID] [VARCHAR](50) NULL,
    [UNITOFMEASUREID] [VARCHAR](50) NULL,
    [UNITOFMEASURENAME] [VARCHAR](50) NULL,
    [STOCKTYPEID] [INT] NULL,
    [STOCKTYPENAME] [VARCHAR](50) NULL,
    [UNITCOST] [DECIMAL](10,2) NOT NULL CHECK ([UNITCOST] >= 0),
    [UNITPRICE] [DECIMAL](10,2) NOT NULL CHECK ([UNITPRICE] >= 0),
    [AVAILABLEFORSALEDATE] [DATETIME] NOT NULL,
    [STATUS] [BOOLEAN] NOT NULL,
    CONSTRAINT [FK_PRODUCT_PRODUCTSUBCATEGORY] FOREIGN KEY ([PRODUCTSUBCATEGORYKEY]) REFERENCES [PRODUCTSUBCATEGORY]([PRODUCTSUBCATEGORYKEY])
);

-- Yong Yun Kai Louis 

-- Ang Wei Xuan Senderos 

-- Tan Jun Yu Zavier

-- Arjunan Yohith
