ADO_GROUP1_T01:
  outputs:
    dev:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT_SENDEROS') }}"
      user: "{{ env_var('SNOWFLAKE_USER_SENDEROS') }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD_SENDEROS') }}"
      role: "{{ env_var('SNOWFLAKE_ROLE_SENDEROS') }}"
      database: ADO_GROUP1_DB_RAW
      warehouse: "{{ env_var('SNOWFLAKE_WAREHOUSE') }}"
      schema: "{{ env_var('SNOWFLAKE_SCHEMA') }}"
      threads: 4
  target: dev
