ADO_GROUP1_T01:
  outputs:
    dev:
      account: {secrets.SNOWFLAKE_ACCOUNT_SENDEROS}
      database: ADO_GROUP1_DB_RAW
      password: {secrets.SNOWFLAKE_PASSWORD_SENDEROS}
      role: {secrets.SNOWFLAKE_ROLE_SENDEROS}
      schema: {secrets.SNOWFLAKE_SCHEMA}
      threads: 4
      type: snowflake
      user: {secrets.SNOWFLAKE_USER_SENDEROS}
      warehouse: {secrets.SNOWFLAKE_WAREHOUSE}
  target: dev
