-- Tan Hong Kai S10256928K
CREATE OR REPLACE TABLE PRODUCTCATEGORY (
    PRODUCTCATEGORYKEY INTEGER NOT NULL,
    PRODUCTCATEGORYNAME VARCHAR(150) NOT NULL
);

CREATE OR REPLACE TABLE PRODUCTSUBCATEGORY (
    PRODUCTSUBCATEGORYKEY INTEGER NOT NULL,
    PRODUCTSUBCATEGORYNAME VARCHAR(150) NOT NULL
);

CREATE OR REPLACE TABLE PROMOTION (
    PROMOTIONKEY INTEGER NOT NULL,
    PROMOTIONLABEL INTEGER NOT NULL,
    PROMOTIONNAME VARCHAR(150) NOT NULL,
    DISCOUNTPERCENT DECIMAL(5, 2) NOT NULL,
    PROMOTIONTYPE VARCHAR(100) NOT NULL,
    PROMOTIONCATEGORY VARCHAR(100) NOT NULL
);

CREATE OR REPLACE TABLE SALESTERRITORY (
    SALESTERRITORYKEY INTEGER NOT NULL,
    GEOGRAPHYKEY INTEGER NOT NULL,
    SALESTERRITORYNAME VARCHAR(150) NOT NULL,
    SALESTERRITORYREGION VARCHAR(150) NULL,
    SALESTERRITORYCOUNTRY VARCHAR(150) NULL,
    SALESTERRITORYGROUP VARCHAR(100) NULL,
    SALESTERRITORYLEVEL INTEGER NOT NULL,
    SALESTERRITORYMANAGER INTEGER NOT NULL,
    STATUS VARCHAR(50) NOT NULL
);

CREATE OR REPLACE TABLE PRODUCT (
    PRODUCTKEY INTEGER NOT NULL,
    PRODUCTNAME VARCHAR(150) NOT NULL,
    PRODUCTDESCRIPTION TEXT NULL,
    PRODUCTSUBCATEGORYKEY INTEGER NOT NULL,
    MANUFACTURER VARCHAR(150) NULL,
    BRANDNAME VARCHAR(150) NULL,
    CLASSID INTEGER NULL,
    CLASSNAME VARCHAR(100) NULL,
    STYLEID INTEGER NULL,
    STYLENAME VARCHAR(100) NULL,
    COLORID INTEGER NULL,
    COLORNAME VARCHAR(50) NULL,
    WEIGHT DECIMAL(10,2) NULL,
    WEIGHTUNITMEASUREID VARCHAR(50) NULL,
    UNITOFMEASUREID VARCHAR(50) NULL,
    UNITOFMEASURENAME VARCHAR(50) NULL,
    STOCKTYPEID INTEGER NULL,
    STOCKTYPENAME VARCHAR(50) NULL,
    UNITCOST DECIMAL(10,2) NOT NULL,
    UNITPRICE DECIMAL(10,2) NOT NULL,
    AVAILABLEFORSALEDATE DATETIME NOT NULL,
    STATUS BOOLEAN NOT NULL
);

-- Yong Yun Kai Louis 

CREATE OR REPLACE TABLE EMPLOYEE (
    EMPLOYEEKEY INTEGER NOT NULL,
    PARENTEMPLOYEEKEY INTEGER NULL,
    FIRSTNAME VARCHAR(150) NOT NULL,
    LASTNAME VARCHAR(150) NOT NULL,
    TITLE VARCHAR(100) NULL,
    HIREDATE DATE NOT NULL,
    BIRTHDATE DATE NOT NULL,
    EMAILADDRESS VARCHAR(150) NOT NULL,
    PHONE VARCHAR(15) NULL,
    EMERGENCYCONTACTNAME VARCHAR(150),
    EMERGENCYCONTACTPHONE VARCHAR(15),
    GENDER VARCHAR(10) NULL,
    PAYFREQUENCY INTEGER NOT NULL,
    BASERATE DECIMAL(10,2) NULL,
    VACATIONHOURS INTEGER NOT NULL,
    DEPARTMENTNAME VARCHAR(150) NOT NULL,
    STARTDATE DATE NOT NULL,
    STATUS VARCHAR(50) NOT NULL,
    SALARYSTATUS VARCHAR(50) NOT NULL,
    ISSALESPERSON VARCHAR(3) NOT NULL,
    ISMARRIED VARCHAR(3) NOT NULL
);

CREATE OR REPLACE TABLE ENTITY (
    ENTITKEY INTEGER NOT NULL,
    PARENTENTITYKEY INTEGER NOT NULL,
    PARENTENTITYLABEL VARCHAR(100) NULL,
    ENTITYNAME VARCHAR(100) NOT NULL,
    ENTITYDECRIPTION VARCHAR(100) NULL,
    ENTITYTYPE VARCHAR(100) NULL,
    STARTDATE DATETIME NOT NULL,
    STATUS VARCHAR(50) NOT NULL
)

CREATE OR REPLACE TABLE GEOGRAPHY (
    GEOGRAPHYKEY INTEGER NOT NULL,
    GEOGRAPHYTYPE VARCHAR(50) NOT NULL,
    CONTINENTNAME VARCHAR(100) NULL,
    CITYNAME VARCHAR(100) NULL,
    STATEPROVINCENAME VARCHAR(100) NULL,
    REGIONCOUNTRYNAME VARCHAR(100) NULL
);

CREATE OR REPLACE TABLE MACHINE (
    MACHINEKEY INTEGER NOT NULL,
    STOREKEY INTEGER NOT NULL,
    MACHINETYPE VARCHAR(50) NOT NULL,
    MACHINENAME VARCHAR(150) NOT NULL,
    MACHINEDESCRIPTION TEXT NOT NULL,
    VENDORNAME VARCHAR(150) NOT NULL,
    MACHINEOS VARCHAR(150) NOT NULL,
    MACHINESOURCE VARCHAR(150) NOT NULL,
    MACHINEHARDWARE VARCHAR(150) NOT NULL,
    MACHINESOFTWARE VARCHAR(150) NOT NULL,
    STATUS VARCHAR(50) NOT NULL,
    SERVICESTARTDATE DATETIME NOT NULL,
    DECOMMISSIONDATE DATETIME NULL,
    LASTMODIFIEDDATE DATETIME NOT NULL
);

CREATE OR REPLACE TABLE OUTAGE (
    OUTAGEKEY INTEGER NOT NULL,
    OUTAGENAME VARCHAR(100) NOT NULL,
    OUTAGETYPE VARCHAR(100) NOT NULL,
    OUTAGESUBTYPE VARCHAR(100) NULL,
    OUTAGESUBTYPEDESCRIPTION VARCHAR(100) NULL
);

-- Ang Wei Xuan Senderos 

-- Tan Jun Yu Zavier

CREATE OR REPLACE TABLE INVENTORY (
  INVENTORYKEY INTEGER NOT NULL,
  DATEKEY DATE NOT NULL,
  STOREKEY INTEGER NOT NULL,
  PRODUCTKEY INTEGER NOT NULL,
  CURRENCYKEY INTEGER NOT NULL,
  ONHANDQUANTITY INTEGER NOT NULL,
  ONORDERQUANTITY INTEGER NOT NULL,
  SAFETYSTOCKQUANTITY INTEGER NOT NULL,
  UNITCOST DECIMAL(10, 2) NOT NULL,
  DAYSINSTOCK INTEGER NOT NULL,
  MINDAYSINSTOCK INTEGER NOT NULL,
  MAXDAYSINSTOCK INTEGER NOT NULL,
  AGING INTEGER NOT NULL
);

CREATE OR REPLACE TABLE ONLINESALES (
  ONLINESALESKEY INTEGER NOT NULL,
  DATEKEY DATE NOT NULL,
  STOREKEY INTEGER NOT NULL,
  PRODUCTKEY INTEGER NOT NULL,
  PROMOTIONKEY INTEGER NOT NULL,
  CURRENCYKEY INTEGER NOT NULL,
  CUSTOMERKEY INTEGER NOT NULL,
  SALESORDERNUMBER VARCHAR(50) NOT NULL,
  SALESORDERLINENUMBER INTEGER NOT NULL,
  SALESQUANTITY INTEGER NOT NULL,
  SALESAMOUNT DECIMAL(10, 2) NOT NULL,
  RETURNQUANTITY INTEGER NOT NULL,
  RETURNAMOUNT DECIMAL(10, 2) NOT NULL,
  DISCOUNTQUANTITY INTEGER NOT NULL,
  DISCOUNTAMOUNT DECIMAL(10, 2) NOT NULL,
  TOTALCOST DECIMAL(10, 2) NOT NULL,
  UNITCOST DECIMAL(10, 2) NOT NULL,
  UNITPRICE DECIMAL(10, 2) NOT NULL
);

CREATE OR REPLACE TABLE SCENARIO (
	SCENARIOKEY INTEGER NOT NULL,
	SCENARIONAME VARCHAR(50) NOT NULL
);

CREATE OR REPLACE TABLE STORE (
  STOREKEY INTEGER NOT NULL, 
  GEOGRAPHYKEY INTEGER NOT NULL, 
  STOREMANAGER INTEGER NOT NULL,
  STORETYPE VARCHAR(50) NOT NULL, 
  STORENAME VARCHAR(150) NOT NULL, 
  STATUS BOOLEAN NOT NULL, 
  OPENDATE DATE NOT NULL,
  CLOSEDATE DATE NULL, 
  ENTITYKEY INTEGER NOT NULL, 
  STOREPHONE VARCHAR(20) NOT NULL, 
  STOREFIX VARCHAR(20) NULL, 
  CLOSEREASON VARCHAR(150) NULL, 
  EMPLOYEECOUNT INTEGER NULL, 
  SELLINGAREASIZE INTEGER NOT NULL,
  LASTREMODELDATE DATETIME NULL
);

CREATE OR REPLACE TABLE EXCHANGERATE (
  EXCHANGERATEKEY INTEGER NOT NULL,
  CURRENCYKEY INTEGER NOT NULL,
  DATEKEY DATE NOT NULL,
  AVERAGERATE DECIMAL(15, 6) NOT NULL,
  ENDOFDATERATE DECIMAL(15, 6) NOT NULL
);

-- Arjunan Yohith

CREATE OR REPLACE TABLE SALES (
    SALESKEY INTEGER NOT NULL,
    DATEKEY DATE NOT NULL,
    CHANNELKEY INTEGER NOT NULL,
    STOREKEY INTEGER NOT NULL,
    PRODUCTKEY INTEGER NOT NULL,
    PROMOTIONKEY INTEGER NOT NULL,
    CURRENCYKEY INTEGER NOT NULL,
    UNITCOST DECIMAL(10,2) NOT NULL,
    UNITPRICE DECIMAL(10,2) NOT NULL,
    SALESQUANTITY INTEGER NOT NULL,
    RETURNQUANTITY INTEGER NOT NULL,
    RETURNAMOUNT DECIMAL(10,2) NOT NULL,
    DISCOUNTQUANTITY INTEGER NOT NULL,
    DISCOUNTAMOUNT DECIMAL(10,2) NOT NULL,
    TOTALCOST DECIMAL(10,2) NOT NULL,
    SALESAMOUNT DECIMAL(10,2) NOT NULL
);

CREATE OR REPLACE TABLE SALESQUOTA (
    SALESQUOTAKEY INTEGER NOT NULL,
    CHANNELKEY INTEGER NOT NULL,
    STOREKEY INTEGER NOT NULL,
    PRODUCTKEY INTEGER NOT NULL,
    DATEKEY DATE NOT NULL,
    CURRENCYKEY INTEGER NOT NULL,
    SCENARIOKEY INTEGER NOT NULL,
    SALESQUANTITYQUOTA DECIMAL(10,2) NULL,
    SALESAMOUNTQUOTA DECIMAL(18,4) NULL,
    GROSSMARGINQUOTA DECIMAL(18,4) NULL
);

CREATE OR REPLACE TABLE STRATEGYPLAN (
    STRATEGYPLANKEY INTEGER NOT NULL,
    DATEKEY DATE NOT NULL,
    ENTITYKEY INTEGER NOT NULL,
    SCENARIOKEY INTEGER NOT NULL,
    ACCOUNTKEY INTEGER NOT NULL,
    CURRENCYKEY INTEGER NOT NULL,
    PRODUCTCATEGORYKEY INTEGER NOT NULL,
    AMOUNT DECIMAL(15,4) NOT NULL
);

CREATE OR REPLACE TABLE ITMACHINE (
    ITMACHINEKEY INTEGER NOT NULL,
    MACHINEKEY INTEGER NOT NULL,
    DATEKEY DATE NOT NULL,
    COSTAMOUNT DECIMAL(10,2) NOT NULL,
    COSTTYPE VARCHAR(150) NOT NULL
);

CREATE OR REPLACE TABLE ITSLAS (
    ITSLAKEY INTEGER NOT NULL,
    DATEKEY DATE NOT NULL,
    STOREKEY INTEGER NOT NULL,
    MACHINEKEY INTEGER NOT NULL,
    OUTAGEKEY INTEGER NOT NULL,
    OUTAGESTARTTIME DATETIME NOT NULL,
    OUTAGEENDTIME DATETIME NOT NULL,
    DOWNTIME INTEGER NOT NULL
);


