-- Tan Hong Kai S10256928K
CREATE OR REPLACE TABLE PRODUCTCATEGORY (
    PRODUCTCATEGORYKEY NUMBER(38,0) NOT NULL,
    PRODUCTCATEGORYNAME VARCHAR(150) NOT NULL,
    LOADDATE TIMESTAMP_NTZ(9) NOT NULL,
    UPDATEDATE TIMESTAMP_NTZ(9) NULL
);

CREATE OR REPLACE TABLE PRODUCTSUBCATEGORY (
    PRODUCTSUBCATEGORYKEY NUMBER(38,0) NOT NULL,
    PRODUCTSUBCATEGORYNAME VARCHAR(150) NOT NULL,
    LOADDATE TIMESTAMP_NTZ(9) NOT NULL,
    UPDATEDATE TIMESTAMP_NTZ(9) NULL
);

CREATE OR REPLACE TABLE PROMOTION (
    PROMOTIONKEY NUMBER(38,0) NOT NULL,
    PROMOTIONNAME VARCHAR(150) NOT NULL,
    DISCOUNTPERCENT NUMBER(3,2) NOT NULL,
    PROMOTIONTYPE VARCHAR(100) NOT NULL,
    PROMOTIONCATEGORY VARCHAR(100) NOT NULL,
    LOADDATE TIMESTAMP_NTZ(9) NOT NULL,
    UPDATEDATE TIMESTAMP_NTZ(9) NULL
);

CREATE OR REPLACE TABLE SALESTERRITORY (
    SALESTERRITORYKEY NUMBER(38,0) NOT NULL,
    GEOGRAPHYKEY NUMBER(38,0) NOT NULL,
    SALESTERRITORYNAME VARCHAR(150) NOT NULL,
    SALESTERRITORYREGION VARCHAR(150) NULL,
    SALESTERRITORYCOUNTRY VARCHAR(150) NULL,
    SALESTERRITORYGROUP VARCHAR(100) NULL,
    SALESTERRITORYLEVEL NUMBER(38,0) NOT NULL,
    SALESTERRITORYMANAGER NUMBER(38,0) NOT NULL,
    STATUS VARCHAR(50) NOT NULL,
    LOADDATE TIMESTAMP_NTZ(9) NOT NULL,
    UPDATEDATE TIMESTAMP_NTZ(9) NULL
);

CREATE OR REPLACE TABLE PRODUCT (
    PRODUCTKEY NUMBER(38,0) NOT NULL,
    PRODUCTNAME VARCHAR(150) NOT NULL,
    PRODUCTDESCRIPTION TEXT NULL,
    PRODUCTSUBCATEGORYKEY NUMBER(38,0) NOT NULL,
    MANUFACTURER VARCHAR(150) NULL,
    BRANDNAME VARCHAR(150) NULL,
    CLASSID NUMBER(38,0) NULL,
    CLASSNAME VARCHAR(100) NULL,
    STYLEID NUMBER(38,0) NULL,
    STYLENAME VARCHAR(100) NULL,
    COLORID NUMBER(38,0) NULL,
    COLORNAME VARCHAR(50) NULL,
    WEIGHT NUMBER(10,2) NULL,
    WEIGHTUNITMEASUREID VARCHAR(50) NULL,
    UNITOFMEASUREID VARCHAR(50) NULL,
    UNITOFMEASURENAME VARCHAR(50) NULL,
    STOCKTYPEID NUMBER(38,0) NULL,
    STOCKTYPENAME VARCHAR(50) NULL,
    UNITCOST NUMBER(10,2) NOT NULL,
    UNITPRICE NUMBER(10,2) NOT NULL,
    AVAILABLEFORSALEDATE DATETIME NULL,
    STATUS BOOLEAN NOT NULL,
    LOADDATE TIMESTAMP_NTZ(9) NOT NULL,
    UPDATEDATE TIMESTAMP_NTZ(9) NULL
);

-- Yong Yun Kai Louis 

CREATE OR REPLACE TABLE EMPLOYEE (
    EMPLOYEEKEY NUMBER(38,0) NOT NULL,
    PARENTEMPLOYEEKEY NUMBER(38,0) NOT NULL,
    FIRSTNAME VARCHAR(150) NOT NULL,
    LASTNAME VARCHAR(150) NOT NULL,
    TITLE VARCHAR(100) NULL,
    HIREDATE DATE NOT NULL,
    BIRTHDATE DATE NOT NULL,
    EMAILADDRESS VARCHAR(150) NOT NULL,
    PHONE VARCHAR(20) NULL,
    EMERGENCYCONTACTNAME VARCHAR(150),
    EMERGENCYCONTACTPHONE VARCHAR(20),
    GENDER VARCHAR(10) NULL,
    PAYFREQUENCY NUMBER(38,0) NOT NULL,
    BASERATE NUMBER(10,2) NULL,
    VACATIONHOURS NUMBER(38,0) NOT NULL,
    DEPARTMENTNAME VARCHAR(150) NOT NULL,
    STARTDATE DATE NOT NULL,
    STATUS VARCHAR(50) NOT NULL,
    SALARYSTATUS VARCHAR(50) NOT NULL,
    ISSALESPERSON VARCHAR(3) NOT NULL,
    ISMARRIED VARCHAR(3) NOT NULL,
    LOADDATE TIMESTAMP_NTZ(9) NOT NULL,
    UPDATEDATE TIMESTAMP_NTZ(9) NULL
);

CREATE OR REPLACE TABLE ENTITY (
    ENTITYKEY NUMBER(38,0) NOT NULL,
    PARENTENTITYKEY NUMBER(38,0) NOT NULL,
    PARENTENTITYLABEL VARCHAR(100) NULL,
    ENTITYNAME VARCHAR(100) NOT NULL,
    ENTITYDESCRIPTION VARCHAR(100) NULL,
    ENTITYTYPE VARCHAR(100) NULL,
    STARTDATE DATETIME NOT NULL,
    STATUS VARCHAR(50) NOT NULL,
    LOADDATE TIMESTAMP_NTZ(9) NOT NULL,
    UPDATEDATE TIMESTAMP_NTZ(9) NULL
);

CREATE OR REPLACE TABLE GEOGRAPHY (
    GEOGRAPHYKEY INTEGER NOT NULL,
    GEOGRAPHYTYPE VARCHAR(50) NOT NULL,
    CONTINENTNAME VARCHAR(100) NULL,
    CITYNAME VARCHAR(100) NULL,
    STATEPROVINCENAME VARCHAR(100) NULL,
    REGIONCOUNTRYNAME VARCHAR(100) NULL,
    LOADDATE TIMESTAMP_NTZ(9) NOT NULL,
    UPDATEDATE TIMESTAMP_NTZ(9) NULL
);

CREATE OR REPLACE TABLE MACHINE (
    MACHINEKEY NUMBER(38,0) NOT NULL,
    STOREKEY NUMBER(38,0) NOT NULL,
    MACHINETYPE VARCHAR(50) NOT NULL,
    MACHINENAME VARCHAR(150) NOT NULL,
    MACHINEDESCRIPTION VARCHAR(16777216) NOT NULL,
    VENDORNAME VARCHAR(150) NOT NULL,
    MACHINEOS VARCHAR(150) NOT NULL,
    MACHINESOURCE VARCHAR(150) NOT NULL,
    MACHINEHARDWARE VARCHAR(150) NOT NULL,
    MACHINESOFTWARE VARCHAR(150) NOT NULL,
    STATUS VARCHAR(50) NOT NULL,
    SERVICESTARTDATE DATETIME NOT NULL,
    DECOMMISSIONDATE DATETIME NULL,
    LASTMODIFIEDDATE DATETIME NULL,
    LOADDATE TIMESTAMP_NTZ(9) NOT NULL,
    UPDATEDATE TIMESTAMP_NTZ(9) NULL
);

CREATE OR REPLACE TABLE OUTAGE (
    OUTAGEKEY NUMBER(38,0) NOT NULL,
    OUTAGENAME VARCHAR(100) NOT NULL,
    OUTAGETYPE VARCHAR(100) NOT NULL,
    OUTAGESUBTYPE VARCHAR(100) NULL,
    OUTAGESUBTYPEDESCRIPTION VARCHAR(100) NULL,
    LOADDATE TIMESTAMP_NTZ(9) NOT NULL,
    UPDATEDATE TIMESTAMP_NTZ(9) NULL
);

-- Ang Wei Xuan Senderos 
--- ACCOUNT table
CREATE OR REPLACE TABLE ACCOUNT (
    ACCOUNTKEY NUMBER(38,0) NOT NULL,
    PARENTACCOUNTKEY NUMBER(38,0) NOT NULL,
    ACCOUNTNAME VARCHAR(100) NOT NULL,
    ACCOUNTDESCRIPTION VARCHAR(150) NULL,
    ACCOUNTTYPE VARCHAR(50) NOT NULL,
    VALUETYPE VARCHAR(50) NOT NULL,
    CREATIONTIME DATETIME NOT NULL,
    LOADDATE TIMESTAMP_NTZ(9) NOT NULL,
    UPDATEDATE TIMESTAMP_NTZ(9) NULL
);

---CHANNEL table
CREATE OR REPLACE TABLE CHANNEL (
    CHANNELKEY NUMBER(38,0) NOT NULL,
    CHANNELNAME VARCHAR(100) NOT NULL,
    CHANNELDESCRIPTION VARCHAR(100) NULL,
    LOADDATE TIMESTAMP_NTZ(9) NOT NULL,
    UPDATEDATE TIMESTAMP_NTZ(9) NULL
);

---CURRENCY table
CREATE OR REPLACE TABLE CURRENCY (
    CURRENCYKEY NUMBER(38,0) NOT NULL,
    CURRENCYNAME VARCHAR(50) NOT NULL,
    CURRENCYDESCRIPTION VARCHAR(150) NULL,
    LOADDATE TIMESTAMP_NTZ(9) NOT NULL,
    UPDATEDATE TIMESTAMP_NTZ(9) NULL
);

---CUSTOMER table
CREATE OR REPLACE TABLE CUSTOMER (
    CUSTOMERKEY NUMBER(38,0) NOT NULL,
    GEOGRAPHYKEY NUMBER(38,0) NOT NULL,
    FIRSTNAME VARCHAR(100) NOT NULL,
    LASTNAME VARCHAR(100) NOT NULL,
    BIRTHDATE DATE NULL,
    MARITALSTATUS CHAR(1) NULL,
    GENDER CHAR(1) NULL,
    EMAILADDRESS VARCHAR(150) NULL,
    YEARLYINCOME NUMBER(10, 2) NULL,
    TOTALCHILDREN NUMBER(38,0) NULL,
    NUMBERCHILDRENATHOME NUMBER(38,0) NULL,
    EDUCATION VARCHAR(50) NULL,
    OCCUPATION VARCHAR(50) NULL,
    HOUSEOWNERFLAG NUMBER(38,0) NULL,
    NUMBERCARSOWNED NUMBER(38,0) NULL,
    ADDRESSLINE1 VARCHAR(150) NULL,
    PHONE VARCHAR(20) NULL,
    DATEFIRSTPURCHASE DATE NULL,
    CUSTOMERTYPE VARCHAR(50) NULL,
    COMPANYNAME VARCHAR(150) NULL,
    LOADDATE TIMESTAMP_NTZ(9) NOT NULL,
    UPDATEDATE TIMESTAMP_NTZ(9) NULL
);

---DATE table
CREATE OR REPLACE TABLE DATE (
    DATEKEY DATE NOT NULL,
    CALENDARYEAR NUMBER(38,0) NOT NULL,
    CALENDARYEARLABEL VARCHAR(50) NULL,
    CALENDARHALFYEARLABEL CHAR(2) NULL,
    CALENDARQUARTERLABEL CHAR(2) NULL,
    CALENDARMONTHLABEL VARCHAR(20) NULL,
    CALENDARWEEKLABEL VARCHAR(10) NULL,
    CALENDARDAYOFWEEKLABEL VARCHAR(15) NULL,
    FISCALYEAR NUMBER(38,0) NOT NULL,
    FISCALYEARLABEL VARCHAR(50) NULL,
    FISCALHALFYEARLABEL CHAR(2) NULL,
    FISCALQUARTERLABEL CHAR(2) NULL,
    FISCALMONTHLABEL VARCHAR(10) NULL,
    ISWORKDAY VARCHAR(10) NULL,
    ISHOLIDAY VARCHAR(3) NULL,
    EUROPESEASON VARCHAR(50) NULL,
    NORTHAMERICASEASON VARCHAR(50) NULL,
    ASIASEASON VARCHAR(50) NULL,
    MONTHNUMBER NUMBER(38,0) NOT NULL,
    CALENDARDAYOFWEEKNUMBER NUMBER(38,0) NOT NULL,
    LOADDATE TIMESTAMP_NTZ(9) NOT NULL,
    UPDATEDATE TIMESTAMP_NTZ(9) NULL
);

-- Tan Jun Yu Zavier

CREATE OR REPLACE TABLE INVENTORY (
  INVENTORYKEY NUMBER(38,0) NOT NULL,
  DATEKEY DATE NOT NULL,
  STOREKEY NUMBER(38,0) NOT NULL,
  PRODUCTKEY NUMBER(38,0) NOT NULL,
  CURRENCYKEY NUMBER(38,0) NOT NULL,
  ONHANDQUANTITY NUMBER(38,0) NOT NULL,
  ONORDERQUANTITY NUMBER(38,0) NOT NULL,
  SAFETYSTOCKQUANTITY NUMBER(38,0) NOT NULL,
  UNITCOST NUMBER(10, 2) NOT NULL,
  DAYSINSTOCK NUMBER(38,0) NOT NULL,
  MINDAYINSTOCK NUMBER(38,0) NOT NULL,
  MAXDAYINSTOCK NUMBER(38,0) NOT NULL,
  AGING NUMBER(38,0) NOT NULL,
  LOADDATE TIMESTAMP_NTZ(9) NOT NULL,
  UPDATEDATE TIMESTAMP_NTZ(9) NULL
);

CREATE OR REPLACE TABLE ONLINESALES (
  ONLINESALESKEY NUMBER(38,0) NOT NULL,
  DATEKEY DATE NOT NULL,
  STOREKEY NUMBER(38,0) NOT NULL,
  PRODUCTKEY NUMBER(38,0) NOT NULL,
  PROMOTIONKEY NUMBER(38,0) NOT NULL,
  CURRENCYKEY NUMBER(38,0) NOT NULL,
  CUSTOMERKEY NUMBER(38,0) NOT NULL,
  SALESORDERNUMBER VARCHAR(50) NOT NULL,
  SALESORDERLINENUMBER NUMBER(38,0) NOT NULL,
  SALESQUANTITY NUMBER(38,0) NOT NULL,
  SALESAMOUNT NUMBER(10, 2) NOT NULL,
  RETURNQUANTITY NUMBER(38,0) NOT NULL,
  RETURNAMOUNT NUMBER(10, 2) NOT NULL,
  DISCOUNTQUANTITY NUMBER(38,0) NOT NULL,
  DISCOUNTAMOUNT NUMBER(10, 2) NOT NULL,
  TOTALCOST DECIMAL(10, 2) NOT NULL,
  UNITCOST DECIMAL(10, 2) NOT NULL,
  UNITPRICE DECIMAL(10, 2) NOT NULL,
  LOADDATE TIMESTAMP_NTZ(9) NOT NULL,
  UPDATEDATE TIMESTAMP_NTZ(9) NULL

);

CREATE OR REPLACE TABLE SCENARIO (
  SCENARIOKEY NUMBER(38,0) NOT NULL,
  SCENARIONAME VARCHAR(50) NOT NULL,
  LOADDATE TIMESTAMP_NTZ(9) NOT NULL,
  UPDATEDATE TIMESTAMP_NTZ(9) NULL
);

CREATE OR REPLACE TABLE STORE (
  STOREKEY NUMBER(38,0) NOT NULL, 
  GEOGRAPHYKEY NUMBER(38,0) NOT NULL, 
  STOREMANAGER NUMBER(38,0) NOT NULL,
  STORETYPE VARCHAR(50) NOT NULL, 
  STORENAME VARCHAR(150) NOT NULL, 
  STATUS BOOLEAN NOT NULL, 
  OPENDATE DATE NOT NULL,
  CLOSEDATE DATE NULL, 
  ENTITYKEY NUMBER(38,0) NOT NULL, 
  STOREPHONE VARCHAR(20) NOT NULL, 
  STOREFAX VARCHAR(20) NOT NULL, 
  CLOSEREASON VARCHAR(150) NULL, 
  EMPLOYEECOUNT NUMBER(38,0) NULL, 
  SELLINGAREASIZE NUMBER(38,0) NOT NULL,
  LASTREMODELDATE DATETIME NULL,
  LOADDATE TIMESTAMP_NTZ(9) NOT NULL,
  UPDATEDATE TIMESTAMP_NTZ(9) NULL
);

CREATE OR REPLACE TABLE EXCHANGERATE (
  EXCHANGERATEKEY NUMBER(38,0) NOT NULL,
  CURRENCYKEY NUMBER(38,0) NOT NULL,
  DATEKEY DATE NOT NULL,
  AVERAGERATE NUMBER(15, 6) NOT NULL,
  ENDOFDAYRATE NUMBER(15, 6) NOT NULL,
  LOADDATE TIMESTAMP_NTZ(9) NOT NULL,
  UPDATEDATE TIMESTAMP_NTZ(9) NULL
);

-- Arjunan Yohith

CREATE OR REPLACE TABLE SALES (
    SALESKEY NUMBER(38,0) NOT NULL,
    DATEKEY DATE NOT NULL,
    CHANNELKEY NUMBER(38,0) NOT NULL,
    STOREKEY NUMBER(38,0) NOT NULL,
    PRODUCTKEY NUMBER(38,0) NOT NULL,
    PROMOTIONKEY NUMBER(38,0) NOT NULL,
    CURRENCYKEY NUMBER(38,0) NOT NULL,
    UNITCOST NUMBER(10,2) NOT NULL,
    UNITPRICE NUMBER(10,2) NOT NULL,
    SALESQUANTITY NUMBER(38,0) NOT NULL,
    RETURNQUANTITY NUMBER(38,0) NOT NULL,
    RETURNAMOUNT NUMBER(10,2) NOT NULL,
    DISCOUNTQUANTITY NUMBER(38,0) NOT NULL,
    DISCOUNTAMOUNT NUMBER(10,2) NOT NULL,
    TOTALCOST NUMBER(10,2) NOT NULL,
    SALESAMOUNT NUMBER(10,2) NOT NULL,
    LOADDATE TIMESTAMP_NTZ(9) NOT NULL,
    UPDATEDATE TIMESTAMP_NTZ(9) NULL
);

CREATE OR REPLACE TABLE SALESQUOTA (
    SALESQUOTAKEY NUMBER(38,0) NOT NULL,
    CHANNELKEY NUMBER(38,0) NOT NULL,
    STOREKEY NUMBER(38,0) NOT NULL,
    PRODUCTKEY NUMBER(38,0) NOT NULL,
    DATEKEY DATE NOT NULL,
    CURRENCYKEY NUMBER(38,0) NOT NULL,
    SCENARIOKEY NUMBER(38,0) NOT NULL,
    SALESQUANTITYQUOTA NUMBER(38,0) NULL,
    SALESAMOUNTQUOTA NUMBER(18,2) NULL,
    GROSSMARGINQUOTA NUMBER(18,2) NULL,
    LOADDATE TIMESTAMP_NTZ(9) NOT NULL,
    UPDATEDATE TIMESTAMP_NTZ(9) NULL
);

CREATE OR REPLACE TABLE STRATEGYPLAN (
    STRATEGYPLANKEY NUMBER(38,0) NOT NULL,
    DATEKEY DATE NOT NULL,
    ENTITYKEY NUMBER(38,0) NOT NULL,
    SCENARIOKEY NUMBER(38,0) NOT NULL,
    ACCOUNTKEY NUMBER(38,0) NOT NULL,
    CURRENCYKEY NUMBER(38,0) NOT NULL,
    PRODUCTCATEGORYKEY NUMBER(38,0) NOT NULL,
    AMOUNT NUMBER(15,4) NOT NULL,
    LOADDATE TIMESTAMP_NTZ(9) NOT NULL,
    UPDATEDATE TIMESTAMP_NTZ(9) NULL,
);

CREATE OR REPLACE TABLE ITMACHINE (
    ITMACHINEKEY NUMBER(38,0) NOT NULL,
    MACHINEKEY NUMBER(38,0) NOT NULL,
    DATEKEY DATE NOT NULL,
    COSTAMOUNT NUMBER(10,2) NOT NULL,
    COSTTYPE VARCHAR(150) NOT NULL,
    LOADDATE TIMESTAMP_NTZ(9) NOT NULL,
    UPDATEDATE TIMESTAMP_NTZ(9) NULL
);

CREATE OR REPLACE TABLE ITSLA (
    ITSLAKEY NUMBER(38,0) NOT NULL,
    DATEKEY DATE NOT NULL,
    STOREKEY NUMBER(38,0) NOT NULL,
    MACHINEKEY NUMBER(38,0) NOT NULL,
    OUTAGEKEY NUMBER(38,0) NOT NULL,
    OUTAGESTARTTIME DATETIME NOT NULL,
    OUTAGEENDTIME DATETIME NOT NULL,
    DOWNTIME NUMBER(38,0) NOT NULL,
    LOADDATE TIMESTAMP_NTZ(9) NOT NULL,
    UPDATEDATE TIMESTAMP_NTZ(9) NULL
);


