name: Airflow CI with Fixer and Re-Linter

on:
  push:
    branches:
      - main  # Trigger only on pushes to the 'main' branch

jobs:
  validate-and-fix-dags:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # Needed to commit fixes

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      # Install dependencies
      - name: Install dependencies
        run: |
          pip install flake8 pytest pytest-airflow autopep8

      # Run flake8 to lint DAGs
      - name: Lint DAG code
        continue-on-error: true  # Ensures the workflow does not stop on errors
        run: flake8 airflow_dag/dags/

      # Fix linting issues automatically
      - name: Fix linting issues with autopep8
        run: autopep8 --in-place --recursive airflow_dag/dags/

      # Re-run flake8 to ensure fixes were applied
      - name: Re-lint DAG code
        run: flake8 airflow_dag/dags/

      # Check if any changes were made and commit them
      - name: Commit changes if fixes were applied
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add airflow_dag/dags/
          git diff --cached --quiet || git commit -m "fix: Automatically fixed linting issues in DAGs"
          git push origin main
