name: Airflow DAG Linter

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Install graphviz system dependency
      - name: Install graphviz
        run: sudo apt-get update && sudo apt-get install -y graphviz

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      # Install Python dependencies
      - name: Install dependencies
        run: |
          pip install apache-airflow
          pip install apache-airflow[cncf.kubernetes]
          pip install pandas graphviz

      # Disable example DAGs
      - name: Disable example DAGs
        run: |
          export AIRFLOW_HOME=$(pwd)/airflow_home
          mkdir -p $AIRFLOW_HOME
          echo -e "[core]\nload_examples = False" > $AIRFLOW_HOME/airflow.cfg

      # Initialize Airflow database
      - name: Initialize Airflow database
        run: |
          export AIRFLOW_HOME=$(pwd)/airflow_home
          airflow db init

      # Validate DAG files
      - name: Validate DAG files
        run: |
          export AIRFLOW_HOME=$(pwd)/airflow_home
          for file in airflow_dag/*.py; do
            if python -c "import os; from airflow import models; from importlib import import_module; import_module(os.path.splitext('$file')[0].replace('/', '.'))"; then
              echo "Validating $(basename $file)"
              airflow dags test $(basename $file .py) 2023-01-01
            else
              echo "Skipping $file: Not a valid DAG."
            fi
          done
