name: Airflow CI/CD

on:
  push:
    paths:
      - 'Group1_ADO_T01/airflow_dag/dags/**' # Trigger only if DAG files are modified

jobs:
  validate-and-deploy-dags:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      # Install dependencies
      - name: Install dependencies
        run: |
          pip install flake8 pytest pytest-airflow

      # Lint DAGs
      - name: Lint DAG code
        run: |
          flake8 Group1_ADO_T01/airflow_dag/dags/

      # Validate DAGs
      - name: Validate DAGs
        run: |
          airflow dags test orchestrate_dbt_to_snowflake 2023-01-01
          airflow dags test orchestrate_s3_to_snowflake 2023-01-01

      # Deploy DAGs to Airflow
      - name: Deploy DAGs to Airflow
        run: |
          scp -r Group1_ADO_T01/airflow_dag/dags/ user@your-airflow-instance:/path/to/dags/
