name: Trigger dbt Cloud Job

on:
  push:
    branches:
      - main
      - development # Trigger only on pushes to the 'development' branch

    paths:
      - 'models/**'       # Trigger for changes in dbt models
      - 'dbt_project.yml' # Trigger for changes in dbt_project.yml

jobs:
  trigger_dbt_job:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger dbt Cloud Job
        env:
          DBT_CLOUD_API_TOKEN: ${{ secrets.DBT_CLOUD_API_TOKEN }}
          DBT_ACCOUNT_ID: ${{ secrets.DBT_ACCOUNT_ID_SENDEROS }}
          DBT_JOB_ID: ${{ secrets.DBT_JOB_ID_SENDEROS }}
        run: |
          curl -X POST "https://cloud.getdbt.com/api/v2/accounts/${DBT_ACCOUNT_ID}/jobs/${DBT_JOB_ID}/run/" \
          -H "Authorization: Bearer ${DBT_CLOUD_API_TOKEN}" \
          -H "Content-Type: application/json" \
          -d '{"cause": "Triggered via GitHub Actions"}'
