name: Lint Mart Models

on: 
  pull_request:
      branches: [main]

jobs:
  lint-models:
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions/setup-python@v2"
        with:
            python-version: "3.8"
      - name: Install SQLFluff
        run: "pip install sqlfluff==0.12.0"
      - name: Lint models
        run: "sqlfluff lint models/mart/contoso"
