name: Python CI with Build

on:
  push:
    branches:
      - main
  pull_request: {}

jobs:
  python-lint-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install flake8 autopep8 build

      - name: Lint Python code
        run: flake8

      - name: Auto-fix Python linting errors
        if: always()
        run: autopep8 --in-place --aggressive --recursive .

      - name: Build Python package
        run: python -m build
