name: Python CI

on:
  push:
    branches:
      - main
  pull_request: {}

jobs:
  python-lint-and-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      # Install dependencies
      - name: Install dependencies
        run: |
          pip install flake8 pytest

      # Lint Python code
      - name: Lint Python code
        run: flake8

      # Run Python unit tests
      - name: Run Python tests
        run: pytest

      # Optional: Package Python code
      - name: Build Python package
        if: always() # Run this step optionally
        run: |
          pip install build
          python -m build
