name: SQL Linter for dbt Models and SnowSQL

on:
  push:
    branches:
      - main
    paths:
      - 'models/**'
      - 'dbt_project.yml'

jobs:
  run_dbt:
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      # Install dbt Snowflake adapter
      - name: Install dbt
        run: |
          pip install dbt-snowflake

      # Dynamically create profiles.yml
      - name: Create profiles.yml
        run: |
          mkdir -p ~/.dbt
          cat <<EOF > ~/.dbt/profiles.yml
          ADO_GROUP1_T01:
            outputs:
              dev:
                type: snowflake
                account: '${{ secrets.SNOWFLAKE_ACCOUNT_SENDEROS }}'
                user: '${{ secrets.SNOWFLAKE_USER_SENDEROS }}'
                password: '${{ secrets.SNOWFLAKE_PASSWORD_SENDEROS }}'
                role: '${{ secrets.SNOWFLAKE_ROLE_SENDEROS }}'
                database: ADO_GROUP1_DB_RAW
                warehouse: '${{ secrets.SNOWFLAKE_WAREHOUSE }}'
                schema: '${{ secrets.SNOWFLAKE_SCHEMA }}'
                threads: 4
            target: dev
          EOF

      # Run dbt debug
      - name: Debug dbt
        run: dbt debug

      # Run dbt commands (e.g., dbt run, dbt test)
      - name: Run dbt models
        run: dbt run
