name: SQL Linter for dbt Models and SnowSQL

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      # Install sqlfluff with dbt and dbt-snowflake
      - name: Install sqlfluff and dbt-snowflake
        run: |
          pip install sqlfluff sqlfluff-templater-dbt
          pip install dbt-snowflake

      # Move profiles.yml to ~/.dbt/
      - name: Set up dbt profiles.yml
        run: |
          mkdir -p ~/.dbt
          cp profiles.yml ~/.dbt/profiles.yml

      # Debug dbt setup
      - name: Debug dbt setup
        run: dbt debug

      # Lint SQL files
      - name: Lint dbt SQL models and SnowSQL files
        run: sqlfluff lint .

      # Fix SQL issues (optional)
      - name: Fix SQL issues
        run: sqlfluff fix .
