name: SQL Linter

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Python environment (sqlfluff is a Python package)
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      # Install sqlfluff
      - name: Install sqlfluff
        run: pip install sqlfluff

      # Run sqlfluff linter
      - name: Run sqlfluff
        run: sqlfluff lint .