name: Workflow Linter

on:
  push:
    branches:
      - main
      - development # Trigger only on pushes to the 'development' branch

  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Install actionlint
      - name: Install actionlint
        run: |
          curl -sSfL https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash | bash
          sudo mv actionlint /usr/local/bin

      # Lint workflow files
      - name: Lint GitHub Actions workflows
        run: actionlint
