---
    name: Workflow Linter
    
    on:
      push:
        branches:
          - main
      pull_request: {}
    
    jobs:
      lint:
        runs-on: ubuntu-latest
    
        steps:
          # Checkout the repository
          - name: Checkout repository
            uses: actions/checkout@v3
    
          # Install yamllint
          - name: Install yamllint
            run: pip install yamllint
    
          # Lint workflow files
          - name: Lint GitHub workflows
            run: yamllint .github/workflows/
    
    # Ensure there is a blank line at the end
    