-- Tan Hong Kai S10256928K

WITH customer_dates AS (
    SELECT
        CUSTOMERKEY,
        DATEFIRSTPURCHASE,
        CURRENT_DATE AS TODAY
    FROM {{ ref('stg_customers') }}
),
DAYSSINCEFIRSTPURCHASE AS (
    SELECT
        CUSTOMERKEY,
        DATE_DIFF('day', DATEFIRSTPURCHASE, TODAY) AS DAYSSINCEFIRSTPURCHASE
    FROM customer_dates
)
SELECT *
FROM DAYSSINCEFIRSTPURCHASE;